################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Projects/STM32746G-Discovery/Demonstration/Core/Src/k_bsp.c \
C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Projects/STM32746G-Discovery/Demonstration/Core/Src/k_menu.c \
C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Projects/STM32746G-Discovery/Demonstration/Core/Src/k_module.c \
C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Projects/STM32746G-Discovery/Demonstration/Core/Src/k_rtc.c \
C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Projects/STM32746G-Discovery/Demonstration/Core/Src/k_startup.c \
C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Projects/STM32746G-Discovery/Demonstration/Core/Src/k_storage.c \
C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Projects/STM32746G-Discovery/Demonstration/Core/Src/main.c \
C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Projects/STM32746G-Discovery/Demonstration/Core/Src/stm32f7xx_hal_timebase_tim.c \
C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Projects/STM32746G-Discovery/Demonstration/Core/Src/stm32f7xx_it.c 

OBJS += \
./Application/User/Core/k_bsp.o \
./Application/User/Core/k_menu.o \
./Application/User/Core/k_module.o \
./Application/User/Core/k_rtc.o \
./Application/User/Core/k_startup.o \
./Application/User/Core/k_storage.o \
./Application/User/Core/main.o \
./Application/User/Core/stm32f7xx_hal_timebase_tim.o \
./Application/User/Core/stm32f7xx_it.o 

C_DEPS += \
./Application/User/Core/k_bsp.d \
./Application/User/Core/k_menu.d \
./Application/User/Core/k_module.d \
./Application/User/Core/k_rtc.d \
./Application/User/Core/k_startup.d \
./Application/User/Core/k_storage.d \
./Application/User/Core/main.d \
./Application/User/Core/stm32f7xx_hal_timebase_tim.d \
./Application/User/Core/stm32f7xx_it.d 


# Each subdirectory must supply rules for building sources it contributes
Application/User/Core/k_bsp.o: C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Projects/STM32746G-Discovery/Demonstration/Core/Src/k_bsp.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo %cd%
	arm-none-eabi-gcc -mcpu=cortex-m7 -mthumb -mfloat-abi=hard -mfpu=fpv5-sp-d16 -DSTM32F746xx -D_SYS_TIME_H_ -D_TIMEVAL_DEFINED -DUSE_HAL_DRIVER -DUSE_STM32746G_DISCOVERY -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Projects/STM32746G-Discovery/Demonstration/STemWin_Addons" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Projects/STM32746G-Discovery/Demonstration/Config" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Projects/STM32746G-Discovery/Demonstration/Core/inc" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Projects/STM32746G-Discovery/Demonstration/Modules/vnc_server" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Utilities/CPU" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Drivers/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Drivers/STM32F7xx_HAL_Driver/Inc" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Drivers/BSP/STM32746G-Discovery" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Drivers/BSP/Components" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Drivers/BSP/Components/Common" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Middlewares/ST/STM32_USB_Host_Library/Core/Inc" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Middlewares/ST/STM32_USB_Host_Library/Class/MSC/Inc" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Middlewares/ST/STM32_USB_Device_Library/Class/MSC/Inc" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Middlewares/Third_Party/LwIP/src/include" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Middlewares/Third_Party/LwIP/system" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Middlewares/Third_Party/LwIP/system/OS" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Middlewares/ST/STemWin/inc" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Middlewares/Third_Party/FatFs/src" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Middlewares/Third_Party/FatFs/src/drivers" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Middlewares/Third_Party/FreeRTOS/Source/include" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Projects/STM32746G-Discovery/Demonstration/Modules/audio_player/Addons/SpiritDSP_Equalizer" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Projects/STM32746G-Discovery/Demonstration/Modules/audio_player/Addons/SpiritDSP_LoudnessControl" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Drivers/CMSIS/Include"  -O0 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Application/User/Core/k_menu.o: C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Projects/STM32746G-Discovery/Demonstration/Core/Src/k_menu.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo %cd%
	arm-none-eabi-gcc -mcpu=cortex-m7 -mthumb -mfloat-abi=hard -mfpu=fpv5-sp-d16 -DSTM32F746xx -D_SYS_TIME_H_ -D_TIMEVAL_DEFINED -DUSE_HAL_DRIVER -DUSE_STM32746G_DISCOVERY -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Projects/STM32746G-Discovery/Demonstration/STemWin_Addons" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Projects/STM32746G-Discovery/Demonstration/Config" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Projects/STM32746G-Discovery/Demonstration/Core/inc" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Projects/STM32746G-Discovery/Demonstration/Modules/vnc_server" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Utilities/CPU" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Drivers/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Drivers/STM32F7xx_HAL_Driver/Inc" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Drivers/BSP/STM32746G-Discovery" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Drivers/BSP/Components" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Drivers/BSP/Components/Common" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Middlewares/ST/STM32_USB_Host_Library/Core/Inc" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Middlewares/ST/STM32_USB_Host_Library/Class/MSC/Inc" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Middlewares/ST/STM32_USB_Device_Library/Class/MSC/Inc" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Middlewares/Third_Party/LwIP/src/include" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Middlewares/Third_Party/LwIP/system" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Middlewares/Third_Party/LwIP/system/OS" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Middlewares/ST/STemWin/inc" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Middlewares/Third_Party/FatFs/src" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Middlewares/Third_Party/FatFs/src/drivers" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Middlewares/Third_Party/FreeRTOS/Source/include" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Projects/STM32746G-Discovery/Demonstration/Modules/audio_player/Addons/SpiritDSP_Equalizer" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Projects/STM32746G-Discovery/Demonstration/Modules/audio_player/Addons/SpiritDSP_LoudnessControl" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Drivers/CMSIS/Include"  -O0 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Application/User/Core/k_module.o: C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Projects/STM32746G-Discovery/Demonstration/Core/Src/k_module.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo %cd%
	arm-none-eabi-gcc -mcpu=cortex-m7 -mthumb -mfloat-abi=hard -mfpu=fpv5-sp-d16 -DSTM32F746xx -D_SYS_TIME_H_ -D_TIMEVAL_DEFINED -DUSE_HAL_DRIVER -DUSE_STM32746G_DISCOVERY -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Projects/STM32746G-Discovery/Demonstration/STemWin_Addons" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Projects/STM32746G-Discovery/Demonstration/Config" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Projects/STM32746G-Discovery/Demonstration/Core/inc" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Projects/STM32746G-Discovery/Demonstration/Modules/vnc_server" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Utilities/CPU" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Drivers/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Drivers/STM32F7xx_HAL_Driver/Inc" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Drivers/BSP/STM32746G-Discovery" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Drivers/BSP/Components" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Drivers/BSP/Components/Common" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Middlewares/ST/STM32_USB_Host_Library/Core/Inc" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Middlewares/ST/STM32_USB_Host_Library/Class/MSC/Inc" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Middlewares/ST/STM32_USB_Device_Library/Class/MSC/Inc" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Middlewares/Third_Party/LwIP/src/include" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Middlewares/Third_Party/LwIP/system" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Middlewares/Third_Party/LwIP/system/OS" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Middlewares/ST/STemWin/inc" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Middlewares/Third_Party/FatFs/src" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Middlewares/Third_Party/FatFs/src/drivers" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Middlewares/Third_Party/FreeRTOS/Source/include" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Projects/STM32746G-Discovery/Demonstration/Modules/audio_player/Addons/SpiritDSP_Equalizer" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Projects/STM32746G-Discovery/Demonstration/Modules/audio_player/Addons/SpiritDSP_LoudnessControl" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Drivers/CMSIS/Include"  -O0 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Application/User/Core/k_rtc.o: C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Projects/STM32746G-Discovery/Demonstration/Core/Src/k_rtc.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo %cd%
	arm-none-eabi-gcc -mcpu=cortex-m7 -mthumb -mfloat-abi=hard -mfpu=fpv5-sp-d16 -DSTM32F746xx -D_SYS_TIME_H_ -D_TIMEVAL_DEFINED -DUSE_HAL_DRIVER -DUSE_STM32746G_DISCOVERY -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Projects/STM32746G-Discovery/Demonstration/STemWin_Addons" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Projects/STM32746G-Discovery/Demonstration/Config" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Projects/STM32746G-Discovery/Demonstration/Core/inc" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Projects/STM32746G-Discovery/Demonstration/Modules/vnc_server" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Utilities/CPU" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Drivers/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Drivers/STM32F7xx_HAL_Driver/Inc" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Drivers/BSP/STM32746G-Discovery" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Drivers/BSP/Components" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Drivers/BSP/Components/Common" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Middlewares/ST/STM32_USB_Host_Library/Core/Inc" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Middlewares/ST/STM32_USB_Host_Library/Class/MSC/Inc" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Middlewares/ST/STM32_USB_Device_Library/Class/MSC/Inc" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Middlewares/Third_Party/LwIP/src/include" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Middlewares/Third_Party/LwIP/system" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Middlewares/Third_Party/LwIP/system/OS" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Middlewares/ST/STemWin/inc" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Middlewares/Third_Party/FatFs/src" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Middlewares/Third_Party/FatFs/src/drivers" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Middlewares/Third_Party/FreeRTOS/Source/include" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Projects/STM32746G-Discovery/Demonstration/Modules/audio_player/Addons/SpiritDSP_Equalizer" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Projects/STM32746G-Discovery/Demonstration/Modules/audio_player/Addons/SpiritDSP_LoudnessControl" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Drivers/CMSIS/Include"  -O0 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Application/User/Core/k_startup.o: C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Projects/STM32746G-Discovery/Demonstration/Core/Src/k_startup.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo %cd%
	arm-none-eabi-gcc -mcpu=cortex-m7 -mthumb -mfloat-abi=hard -mfpu=fpv5-sp-d16 -DSTM32F746xx -D_SYS_TIME_H_ -D_TIMEVAL_DEFINED -DUSE_HAL_DRIVER -DUSE_STM32746G_DISCOVERY -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Projects/STM32746G-Discovery/Demonstration/STemWin_Addons" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Projects/STM32746G-Discovery/Demonstration/Config" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Projects/STM32746G-Discovery/Demonstration/Core/inc" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Projects/STM32746G-Discovery/Demonstration/Modules/vnc_server" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Utilities/CPU" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Drivers/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Drivers/STM32F7xx_HAL_Driver/Inc" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Drivers/BSP/STM32746G-Discovery" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Drivers/BSP/Components" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Drivers/BSP/Components/Common" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Middlewares/ST/STM32_USB_Host_Library/Core/Inc" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Middlewares/ST/STM32_USB_Host_Library/Class/MSC/Inc" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Middlewares/ST/STM32_USB_Device_Library/Class/MSC/Inc" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Middlewares/Third_Party/LwIP/src/include" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Middlewares/Third_Party/LwIP/system" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Middlewares/Third_Party/LwIP/system/OS" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Middlewares/ST/STemWin/inc" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Middlewares/Third_Party/FatFs/src" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Middlewares/Third_Party/FatFs/src/drivers" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Middlewares/Third_Party/FreeRTOS/Source/include" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Projects/STM32746G-Discovery/Demonstration/Modules/audio_player/Addons/SpiritDSP_Equalizer" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Projects/STM32746G-Discovery/Demonstration/Modules/audio_player/Addons/SpiritDSP_LoudnessControl" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Drivers/CMSIS/Include"  -O0 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Application/User/Core/k_storage.o: C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Projects/STM32746G-Discovery/Demonstration/Core/Src/k_storage.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo %cd%
	arm-none-eabi-gcc -mcpu=cortex-m7 -mthumb -mfloat-abi=hard -mfpu=fpv5-sp-d16 -DSTM32F746xx -D_SYS_TIME_H_ -D_TIMEVAL_DEFINED -DUSE_HAL_DRIVER -DUSE_STM32746G_DISCOVERY -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Projects/STM32746G-Discovery/Demonstration/STemWin_Addons" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Projects/STM32746G-Discovery/Demonstration/Config" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Projects/STM32746G-Discovery/Demonstration/Core/inc" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Projects/STM32746G-Discovery/Demonstration/Modules/vnc_server" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Utilities/CPU" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Drivers/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Drivers/STM32F7xx_HAL_Driver/Inc" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Drivers/BSP/STM32746G-Discovery" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Drivers/BSP/Components" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Drivers/BSP/Components/Common" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Middlewares/ST/STM32_USB_Host_Library/Core/Inc" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Middlewares/ST/STM32_USB_Host_Library/Class/MSC/Inc" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Middlewares/ST/STM32_USB_Device_Library/Class/MSC/Inc" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Middlewares/Third_Party/LwIP/src/include" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Middlewares/Third_Party/LwIP/system" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Middlewares/Third_Party/LwIP/system/OS" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Middlewares/ST/STemWin/inc" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Middlewares/Third_Party/FatFs/src" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Middlewares/Third_Party/FatFs/src/drivers" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Middlewares/Third_Party/FreeRTOS/Source/include" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Projects/STM32746G-Discovery/Demonstration/Modules/audio_player/Addons/SpiritDSP_Equalizer" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Projects/STM32746G-Discovery/Demonstration/Modules/audio_player/Addons/SpiritDSP_LoudnessControl" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Drivers/CMSIS/Include"  -O0 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Application/User/Core/main.o: C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Projects/STM32746G-Discovery/Demonstration/Core/Src/main.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo %cd%
	arm-none-eabi-gcc -mcpu=cortex-m7 -mthumb -mfloat-abi=hard -mfpu=fpv5-sp-d16 -DSTM32F746xx -D_SYS_TIME_H_ -D_TIMEVAL_DEFINED -DUSE_HAL_DRIVER -DUSE_STM32746G_DISCOVERY -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Projects/STM32746G-Discovery/Demonstration/STemWin_Addons" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Projects/STM32746G-Discovery/Demonstration/Config" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Projects/STM32746G-Discovery/Demonstration/Core/inc" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Projects/STM32746G-Discovery/Demonstration/Modules/vnc_server" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Utilities/CPU" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Drivers/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Drivers/STM32F7xx_HAL_Driver/Inc" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Drivers/BSP/STM32746G-Discovery" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Drivers/BSP/Components" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Drivers/BSP/Components/Common" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Middlewares/ST/STM32_USB_Host_Library/Core/Inc" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Middlewares/ST/STM32_USB_Host_Library/Class/MSC/Inc" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Middlewares/ST/STM32_USB_Device_Library/Class/MSC/Inc" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Middlewares/Third_Party/LwIP/src/include" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Middlewares/Third_Party/LwIP/system" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Middlewares/Third_Party/LwIP/system/OS" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Middlewares/ST/STemWin/inc" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Middlewares/Third_Party/FatFs/src" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Middlewares/Third_Party/FatFs/src/drivers" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Middlewares/Third_Party/FreeRTOS/Source/include" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Projects/STM32746G-Discovery/Demonstration/Modules/audio_player/Addons/SpiritDSP_Equalizer" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Projects/STM32746G-Discovery/Demonstration/Modules/audio_player/Addons/SpiritDSP_LoudnessControl" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Drivers/CMSIS/Include"  -O0 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Application/User/Core/stm32f7xx_hal_timebase_tim.o: C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Projects/STM32746G-Discovery/Demonstration/Core/Src/stm32f7xx_hal_timebase_tim.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo %cd%
	arm-none-eabi-gcc -mcpu=cortex-m7 -mthumb -mfloat-abi=hard -mfpu=fpv5-sp-d16 -DSTM32F746xx -D_SYS_TIME_H_ -D_TIMEVAL_DEFINED -DUSE_HAL_DRIVER -DUSE_STM32746G_DISCOVERY -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Projects/STM32746G-Discovery/Demonstration/STemWin_Addons" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Projects/STM32746G-Discovery/Demonstration/Config" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Projects/STM32746G-Discovery/Demonstration/Core/inc" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Projects/STM32746G-Discovery/Demonstration/Modules/vnc_server" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Utilities/CPU" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Drivers/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Drivers/STM32F7xx_HAL_Driver/Inc" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Drivers/BSP/STM32746G-Discovery" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Drivers/BSP/Components" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Drivers/BSP/Components/Common" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Middlewares/ST/STM32_USB_Host_Library/Core/Inc" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Middlewares/ST/STM32_USB_Host_Library/Class/MSC/Inc" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Middlewares/ST/STM32_USB_Device_Library/Class/MSC/Inc" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Middlewares/Third_Party/LwIP/src/include" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Middlewares/Third_Party/LwIP/system" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Middlewares/Third_Party/LwIP/system/OS" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Middlewares/ST/STemWin/inc" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Middlewares/Third_Party/FatFs/src" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Middlewares/Third_Party/FatFs/src/drivers" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Middlewares/Third_Party/FreeRTOS/Source/include" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Projects/STM32746G-Discovery/Demonstration/Modules/audio_player/Addons/SpiritDSP_Equalizer" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Projects/STM32746G-Discovery/Demonstration/Modules/audio_player/Addons/SpiritDSP_LoudnessControl" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Drivers/CMSIS/Include"  -O0 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Application/User/Core/stm32f7xx_it.o: C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Projects/STM32746G-Discovery/Demonstration/Core/Src/stm32f7xx_it.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo %cd%
	arm-none-eabi-gcc -mcpu=cortex-m7 -mthumb -mfloat-abi=hard -mfpu=fpv5-sp-d16 -DSTM32F746xx -D_SYS_TIME_H_ -D_TIMEVAL_DEFINED -DUSE_HAL_DRIVER -DUSE_STM32746G_DISCOVERY -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Projects/STM32746G-Discovery/Demonstration/STemWin_Addons" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Projects/STM32746G-Discovery/Demonstration/Config" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Projects/STM32746G-Discovery/Demonstration/Core/inc" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Projects/STM32746G-Discovery/Demonstration/Modules/vnc_server" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Utilities/CPU" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Drivers/CMSIS/Device/ST/STM32F7xx/Include" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Drivers/STM32F7xx_HAL_Driver/Inc" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Drivers/BSP/STM32746G-Discovery" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Drivers/BSP/Components" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Drivers/BSP/Components/Common" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Middlewares/ST/STM32_USB_Host_Library/Core/Inc" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Middlewares/ST/STM32_USB_Host_Library/Class/MSC/Inc" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Middlewares/ST/STM32_USB_Device_Library/Class/MSC/Inc" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Middlewares/Third_Party/LwIP/src/include" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Middlewares/Third_Party/LwIP/system" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Middlewares/Third_Party/LwIP/system/OS" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Middlewares/ST/STemWin/inc" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Middlewares/Third_Party/FatFs/src" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Middlewares/Third_Party/FatFs/src/drivers" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Middlewares/Third_Party/FreeRTOS/Source/include" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Projects/STM32746G-Discovery/Demonstration/Modules/audio_player/Addons/SpiritDSP_Equalizer" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Projects/STM32746G-Discovery/Demonstration/Modules/audio_player/Addons/SpiritDSP_LoudnessControl" -I"C:/Users/Gabriele/Desktop/STM32Cube_FW_F7_V1.7.0/Drivers/CMSIS/Include"  -O0 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


